github:
  repo: https://github.com/sgwanlee/sgwanlee.github.io
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge

gems:
  - jekyll-coffeescript
  - jekyll-paginate

# Dependencies
highlighter:         'pygments'

# Permalinks
permalink:        pretty

# Setup
title:            Dev Blog
tagline:          'Ara-House'
description:      ''
url:              http://sgwanlee.github.io

author:
  name:           'SG Lee'
  url:            https://twitter.com/sgwanlee

paginate:         5